#!/usr/bin/perl

use strict;
use lib 'lib';
use DJabberd;
use DJabberd::Auth::AllowedUsers;
use DJabberd::Auth::StaticPassword;
use DJabberd::Delivery::Local;
use DJabberd::Delivery::S2S;

use Getopt::Long;

use vars qw($DEBUG);
$DEBUG = 0;

my ($daemonize);

Getopt::Long::GetOptions(
    'd|daemon'       => \$daemonize,
    'debug=i'        => \$DEBUG,
   );

my $server = DJabberd->new(
                           #server_name => '207.7.148.210',
                           server_name => 'jabber.bradfitz.com',
                           daemonize => $daemonize,
                           s2s       => 1,
                           plugins   => [
                                         DJabberd::Auth::AllowedUsers->new(policy => "deny",
                                                                           allowed => [qw(brad daveman692 crucially bradfitz bob test revmischa)]),
                                         DJabberd::Auth::StaticPassword->new(password => "password"),
                                         DJabberd::Delivery::Local->new(),
                                         DJabberd::Delivery::S2S->new(),
                                         ],
#                           roster_hooks => [
#                                            DJabberd::Roster::Mysql->new(host => "127.0.0.1",
#                                                                         db => "djabberd_roster"),
#                                            ],
                           );
$server->run;
